-- Substitui os produtos placeholder pelo catalogo real do Stripe: cada linha e um
-- preco ja calculado (custo real DingConnect + margem + buffer de taxas Stripe,
-- ver metadata "cost_eur"/"margin_eur"/"fee_safe" nesses Price/Product no Stripe),
-- referenciado diretamente por stripe_price_id -- sem calculo de cambio no checkout.

ALTER TABLE airtime_products ADD COLUMN stripe_price_id VARCHAR(200);
ALTER TABLE airtime_products ADD COLUMN payer_amount_cents INTEGER;

-- Novas operadoras do Brasil presentes no catalogo Stripe mas ainda nao seedadas.
INSERT INTO operators (country_id, name, code, logo_url, active, provider_code, min_amount, max_amount)
SELECT id, 'Sercomtel', 'SERCOMTEL_BR', 'https://imagerepo.ding.com/logo/7BF18C/BR.png', TRUE, '7BF18CBR', 10, 200 FROM countries WHERE iso_code = 'BR';
INSERT INTO operators (country_id, name, code, logo_url, active, provider_code, min_amount, max_amount)
SELECT id, 'Algar MVNO', 'ALGARMVNO_BR', 'https://imagerepo.ding.com/logo/943DFA/BR.png', TRUE, '943DFABR', 10, 200 FROM countries WHERE iso_code = 'BR';

-- Remove pedidos de teste criados contra os produtos placeholder (pre-lancamento, sem
-- nenhum pagamento real associado -- apenas testes em modo Stripe test) para poder
-- substituir os produtos sem violar a foreign key.
DELETE FROM orders;

-- Remove os produtos placeholder (valores redondos ilustrativos) para todas as operadoras.
DELETE FROM airtime_products;

INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 2244.68, 'AOA', 'AIRTIME', TRUE, 'price_1U8kX07rIGzuqGa9uVQSW7XN', 615 FROM operators WHERE code = 'MOVICEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 5602.89, 'AOA', 'AIRTIME', TRUE, 'price_1U8kX07rIGzuqGa9U9mhul7f', 1102 FROM operators WHERE code = 'MOVICEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 500, 'AOA', 'AIRTIME', TRUE, 'price_1U8kX07rIGzuqGa9MlbC6UcA', 371 FROM operators WHERE code = 'MOVICEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 100, 'AOA', 'AIRTIME', TRUE, 'price_1U8kX07rIGzuqGa9fUF6eqpZ', 307 FROM operators WHERE code = 'MOVICEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 3371.67, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWz7rIGzuqGa99xuiIk8u', 777 FROM operators WHERE code = 'MOVICEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1122.34, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWz7rIGzuqGa99sOcFYHm', 452 FROM operators WHERE code = 'MOVICEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 566.5, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWz7rIGzuqGa9lERaLkXm', 378 FROM operators WHERE code = 'UNITEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 2253.17, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWy7rIGzuqGa9L4suRiYe', 638 FROM operators WHERE code = 'UNITEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 400.79, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWy7rIGzuqGa9Q1vKKkK0', 352 FROM operators WHERE code = 'UNITEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1128.86, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWy7rIGzuqGa9IOPESJsy', 464 FROM operators WHERE code = 'UNITEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 3378.22, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWx7rIGzuqGa9pXkQIUnq', 811 FROM operators WHERE code = 'UNITEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 5627.58, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWx7rIGzuqGa9oQh3gzrP', 1157 FROM operators WHERE code = 'UNITEL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 3000, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWx7rIGzuqGa9IpnrSI4a', 736 FROM operators WHERE code = 'AFRICELL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 100, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWw7rIGzuqGa9fqexihFJ', 306 FROM operators WHERE code = 'AFRICELL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 500, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWw7rIGzuqGa9pVA9NhH8', 365 FROM operators WHERE code = 'AFRICELL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1000, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWw7rIGzuqGa9zjqJzhVg', 440 FROM operators WHERE code = 'AFRICELL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 2000, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWv7rIGzuqGa9BQwqJaSw', 588 FROM operators WHERE code = 'AFRICELL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 5000, 'AOA', 'AIRTIME', TRUE, 'price_1U8kWv7rIGzuqGa9L89oickp', 1033 FROM operators WHERE code = 'AFRICELL_AO';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 30, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWv7rIGzuqGa9Z8bz9i3p', 1012 FROM operators WHERE code = 'ALGAR_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWu7rIGzuqGa9g9kmn36v', 652 FROM operators WHERE code = 'SERCOMTEL_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 50, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWu7rIGzuqGa9eHH9Vgv7', 1493 FROM operators WHERE code = 'ALGAR_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 100, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWu7rIGzuqGa9AROCfEJo', 2695 FROM operators WHERE code = 'ALGAR_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 25, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWt7rIGzuqGa9E4e1WrsA', 892 FROM operators WHERE code = 'ALGAR_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 25, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWt7rIGzuqGa93ZOXBPqU', 892 FROM operators WHERE code = 'SERCOMTEL_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 100, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWt7rIGzuqGa9d0v9TSkT', 2695 FROM operators WHERE code = 'SERCOMTEL_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 30, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWs7rIGzuqGa9SmQa8Uxx', 1012 FROM operators WHERE code = 'ALGARMVNO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 50, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWs7rIGzuqGa9kjugySH3', 1493 FROM operators WHERE code = 'SERCOMTEL_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 40, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWs7rIGzuqGa97afUaf0n', 1253 FROM operators WHERE code = 'ALGARMVNO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWr7rIGzuqGa9E4y789CN', 772 FROM operators WHERE code = 'ALGARMVNO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 35, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWr7rIGzuqGa9JpKWeXUH', 1132 FROM operators WHERE code = 'SERCOMTEL_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 90, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWr7rIGzuqGa93ZpdIy7F', 2454 FROM operators WHERE code = 'ALGARMVNO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 60, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWq7rIGzuqGa9gVjG7hgF', 1733 FROM operators WHERE code = 'ALGARMVNO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 30, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWq7rIGzuqGa9WfqHxFMb', 1014 FROM operators WHERE code = 'CLARO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 180, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWq7rIGzuqGa9chdl8r8n', 4618 FROM operators WHERE code = 'ALGARMVNO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 40, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWp7rIGzuqGa9olvY1Bvr', 1257 FROM operators WHERE code = 'CLARO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWp7rIGzuqGa96K0acsez', 774 FROM operators WHERE code = 'CLARO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 30, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWp7rIGzuqGa9UknFvf4f', 1012 FROM operators WHERE code = 'TIM_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWo7rIGzuqGa9gr9SH04c', 772 FROM operators WHERE code = 'TIM_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 50, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWo7rIGzuqGa9uIQ4C6LU', 1498 FROM operators WHERE code = 'CLARO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 40, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWo7rIGzuqGa9lT2Wlq4o', 1253 FROM operators WHERE code = 'TIM_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 100, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWn7rIGzuqGa9r8uNg3TV', 2707 FROM operators WHERE code = 'CLARO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 25, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWn7rIGzuqGa9QP99Fqvj', 892 FROM operators WHERE code = 'TIM_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 100, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWn7rIGzuqGa9Gqz7aIpH', 2695 FROM operators WHERE code = 'TIM_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 17, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWm7rIGzuqGa9yTgGtEiD', 701 FROM operators WHERE code = 'VIVO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 60, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWf7rIGzuqGa9jQEaLqKs', 1733 FROM operators WHERE code = 'TIM_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWf7rIGzuqGa911I4Bsen', 774 FROM operators WHERE code = 'VIVO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 50, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWe7rIGzuqGa98MeCrqYb', 1492 FROM operators WHERE code = 'TIM_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWe7rIGzuqGa9jk7mvpYS', 653 FROM operators WHERE code = 'VIVO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 30, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWe7rIGzuqGa94xVlQDLj', 1015 FROM operators WHERE code = 'VIVO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 100, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWd7rIGzuqGa93SMHxiTY', 2705 FROM operators WHERE code = 'VIVO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 35, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWd7rIGzuqGa91yOGxrWb', 1135 FROM operators WHERE code = 'VIVO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 25, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWc7rIGzuqGa9Cdzjk6MX', 894 FROM operators WHERE code = 'VIVO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 50, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWc7rIGzuqGa9cLSRWHKr', 1498 FROM operators WHERE code = 'VIVO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 40, 'BRL', 'AIRTIME', TRUE, 'price_1U8kWb7rIGzuqGa9gEr5A6Zn', 1257 FROM operators WHERE code = 'VIVO_BR';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 2000, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWb7rIGzuqGa997SLGDfa', 712 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 2624, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWb7rIGzuqGa9QMhbemSF', 842 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 3280, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWa7rIGzuqGa9hex0f491', 980 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 4920, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWa7rIGzuqGa9zwxgEOFV', 1326 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 19680, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWa7rIGzuqGa9OZpfmIa0', 4433 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 5904, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWZ7rIGzuqGa9P8GhXybk', 1533 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 9840, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWZ7rIGzuqGa9f5SJhWCK', 2362 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 13120, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWZ7rIGzuqGa9OqJDunVh', 3052 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 12464, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWY7rIGzuqGa9OFyudgi5', 2914 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 6560, 'XOF', 'AIRTIME', TRUE, 'price_1U8kWY7rIGzuqGa9bTOVe2LS', 1671 FROM operators WHERE code = 'ORANGE_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 249.9, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWY7rIGzuqGa9Rn8OwiVo', 718 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 49.7, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWX7rIGzuqGa9KBKOjTL6', 375 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 200.2, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWX7rIGzuqGa9Zf4IS5Fi', 633 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 9.8, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWX7rIGzuqGa9BPIUZz7C', 307 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 149.8, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWX7rIGzuqGa9sbS9wDQ1', 547 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 100.1, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWW7rIGzuqGa9e18hB5Ya', 462 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 399.7, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWW7rIGzuqGa9iws5wiw3', 974 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 599.9, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWW7rIGzuqGa9aw7LtrFe', 1317 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 450.1, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWV7rIGzuqGa9dtSOFS2x', 1061 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 499.8, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWV7rIGzuqGa95DSwagHh', 1145 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 350, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWV7rIGzuqGa9bzpdku0x', 889 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 300.3, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWU7rIGzuqGa978d1gXGt', 804 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1099.7, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWU7rIGzuqGa99ZNrknZ8', 2172 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 800.1, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWU7rIGzuqGa95OsbZDwY', 1659 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 900.2, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWT7rIGzuqGa9PGnas0Cn', 1830 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1000.3, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWT7rIGzuqGa9DgN59oAo', 2001 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1199.8, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWT7rIGzuqGa9XlyXrMAw', 2343 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 700, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWS7rIGzuqGa9pFbVol1I', 1488 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1500.1, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWS7rIGzuqGa9UBFPgFpT', 2856 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1299.9, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWS7rIGzuqGa9i8wFbTq3', 2513 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1600.2, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWR7rIGzuqGa97W5mp9hB', 3028 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1799.7, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWR7rIGzuqGa9z3niNND9', 3368 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1700.3, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWR7rIGzuqGa9aDqM7ol5', 3199 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1400, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWQ7rIGzuqGa9JoznJcmh', 2685 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 49.7, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWQ7rIGzuqGa9IwfI39yA', 375 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 100.1, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWQ7rIGzuqGa9bsalcbOO', 462 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1899.8, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWP7rIGzuqGa9PJ2vUQDj', 3540 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 200.2, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWP7rIGzuqGa9o90KFy0N', 633 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1999.9, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWP7rIGzuqGa9D0QEXYjI', 3711 FROM operators WHERE code = 'MOVITEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 149.8, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWO7rIGzuqGa9JWp0fEgC', 547 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 249.9, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWC7rIGzuqGa93of4bJgS', 718 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 499.8, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWC7rIGzuqGa9v99l1u00', 1145 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 450.1, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWC7rIGzuqGa9G0S4bBbY', 1061 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 300.3, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWB7rIGzuqGa9fxHf7o6J', 804 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 350, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWB7rIGzuqGa9hqKZkzwM', 889 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 399.7, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWB7rIGzuqGa9FvUv250k', 974 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 700, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWA7rIGzuqGa9WwjeqKaI', 1488 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 800.1, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWA7rIGzuqGa9PmgWwwYm', 1659 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 900.2, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWA7rIGzuqGa9QtL1k0BN', 1830 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1000.3, 'MZN', 'AIRTIME', TRUE, 'price_1U8kWA7rIGzuqGa9IU12rpi4', 2001 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 599.9, 'MZN', 'AIRTIME', TRUE, 'price_1U8kW97rIGzuqGa9DWza3mFp', 1317 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1199.8, 'MZN', 'AIRTIME', TRUE, 'price_1U8kW97rIGzuqGa9IbdOHsLA', 2343 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1799.7, 'MZN', 'AIRTIME', TRUE, 'price_1U8kW97rIGzuqGa95CjARXjT', 3368 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 10, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW87rIGzuqGa9gNutMWSm', 1739 FROM operators WHERE code = 'LYCAMOBILE_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1700.3, 'MZN', 'AIRTIME', TRUE, 'price_1U8kW87rIGzuqGa9tLWekzNa', 3199 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1500.1, 'MZN', 'AIRTIME', TRUE, 'price_1U8kW87rIGzuqGa9EAzkKa5b', 2856 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 5, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW77rIGzuqGa9BNwTrqp9', 1014 FROM operators WHERE code = 'LYCAMOBILE_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 1999.9, 'MZN', 'AIRTIME', TRUE, 'price_1U8kW77rIGzuqGa94Nb9N7my', 3711 FROM operators WHERE code = 'VODACOM_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 183.75, 'STN', 'AIRTIME', TRUE, 'price_1U8kW77rIGzuqGa9vHUCjQML', 1348 FROM operators WHERE code = 'CST_ST';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 367.5, 'STN', 'AIRTIME', TRUE, 'price_1U8kW67rIGzuqGa91mNEY3Tp', 2407 FROM operators WHERE code = 'CST_ST';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 245, 'STN', 'AIRTIME', TRUE, 'price_1U8kW67rIGzuqGa9sa2VHRhb', 1702 FROM operators WHERE code = 'CST_ST';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW67rIGzuqGa9qtaOmPMg', 3186 FROM operators WHERE code = 'LYCAMOBILE_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW57rIGzuqGa9EYTIfXEX', 2462 FROM operators WHERE code = 'LYCAMOBILE_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 490, 'STN', 'AIRTIME', TRUE, 'price_1U8kW57rIGzuqGa9vwmvJBIF', 3112 FROM operators WHERE code = 'CST_ST';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 10, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW57rIGzuqGa9GdTn7U8T', 1344 FROM operators WHERE code = 'ALOU_CV';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW47rIGzuqGa9zUVNI4dA', 2399 FROM operators WHERE code = 'UNITELT_CV';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 5, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW47rIGzuqGa9hwoEWJFR', 817 FROM operators WHERE code = 'UNITELT_CV';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 10, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW47rIGzuqGa9KOVhATHj', 1344 FROM operators WHERE code = 'UNITELT_CV';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 5, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW37rIGzuqGa9Yev1jtwL', 817 FROM operators WHERE code = 'ALOU_CV';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW37rIGzuqGa9l799fv6X', 1871 FROM operators WHERE code = 'UNITELT_CV';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW37rIGzuqGa9TB9GphIv', 1871 FROM operators WHERE code = 'ALOU_CV';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW27rIGzuqGa9mPK6pOgK', 1871 FROM operators WHERE code = 'MTN_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW27rIGzuqGa97QN3FgyG', 2399 FROM operators WHERE code = 'MTN_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 5, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW27rIGzuqGa9BzV0kzmx', 817 FROM operators WHERE code = 'MTN_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 10, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW27rIGzuqGa9FCCv7EsI', 1344 FROM operators WHERE code = 'MTN_GW';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW17rIGzuqGa9IO56bh76', 2399 FROM operators WHERE code = 'ALOU_CV';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW17rIGzuqGa9a4iZAmeA', 2399 FROM operators WHERE code = 'MEO_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW17rIGzuqGa92IhBANYi', 1871 FROM operators WHERE code = 'MEO_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 5, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW07rIGzuqGa9jajqyHl6', 817 FROM operators WHERE code = 'MCEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 10, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW07rIGzuqGa9yYnw6DEh', 1344 FROM operators WHERE code = 'MCEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kW07rIGzuqGa9MN1Bx1Fz', 1871 FROM operators WHERE code = 'MCEL_MZ';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kVz7rIGzuqGa9wGSH7qHw', 1871 FROM operators WHERE code = 'MOCHE_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kVz7rIGzuqGa9LhQLc8nO', 1871 FROM operators WHERE code = 'UZO_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'EUR', 'AIRTIME', TRUE, 'price_1U8kVz7rIGzuqGa97fPiwlk9', 2399 FROM operators WHERE code = 'UZO_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 10, 'EUR', 'AIRTIME', TRUE, 'price_1U8kVy7rIGzuqGa9U6RgOpD5', 1344 FROM operators WHERE code = 'NOS_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'EUR', 'AIRTIME', TRUE, 'price_1U8kVy7rIGzuqGa92dQYGV4f', 2399 FROM operators WHERE code = 'MOCHE_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kVx7rIGzuqGa9ERIizKeG', 1871 FROM operators WHERE code = 'NOS_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'EUR', 'AIRTIME', TRUE, 'price_1U8kVx7rIGzuqGa9drmJJRgR', 2399 FROM operators WHERE code = 'NOS_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 20, 'EUR', 'AIRTIME', TRUE, 'price_1U8kVx7rIGzuqGa9dlqstEZR', 2399 FROM operators WHERE code = 'VODAFONE_PT';
INSERT INTO airtime_products (operator_id, amount, currency, type, active, stripe_price_id, payer_amount_cents) SELECT id, 15, 'EUR', 'AIRTIME', TRUE, 'price_1U8kVw7rIGzuqGa9ztwL7qqj', 1871 FROM operators WHERE code = 'VODAFONE_PT';
